name: Telegram Bot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python bot.py
    
    - name: Update status
      if: success()
      run: |
        echo '{"status": "online", "last_update": "'$(date -u '+%Y-%m-%d %H:%M:%S UTC')'" }' > status.json
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add status.json
        git commit -m "Update bot status" || echo "No changes to commit"
        git push