name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot google-generativeai
    - name: Run bot
      env:
        API_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: python bot.py